name: json_serializable_kt_typehelpers
description: A starting point for Dart libraries or applications.
version: 3.0.0
homepage: https://github.com/knaeckeKami/json_serializable_immutable_collections/tree/master/


environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  kt_dart: ^0.9.0
  json_serializable_type_helper_utils: ^5.0.0
  # json_serializable_type_helper_utils:
  #   path: ../json_serializable_type_helper_utils
  source_gen: ^1.0.0
  analyzer: "^2.0.0"


dev_dependencies:
   test: any
