name: json_serializable_built_typehelpers
description: typehelpers for built_collection, used for json_serializable.
version: 3.1.2
homepage: https://github.com/knaeckeKami/json_serializable_immutable_collections/tree/master/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  json_serializable_type_helper_utils: ^5.1.2
  source_gen: ^1.0.0
  analyzer: '>=3.0.0 <6.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.4
