name: json_serializable_mobx
description: Adding support for mobx collections for json_serializable
version: 0.10.0
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  mobx: ^2.0.1

dependencies:
  json_serializable:  ^6.0.1
  json_annotation:  ^4.3.0
  build_runner: ^2.0.5
  analyzer: ^2.0.0
  source_gen: ^1.0.2
  build: ^2.0.0
  json_serializable_mobx_typehelpers: ^3.0.0
  # json_serializable_mobx_typehelpers:
  #  path: ../../typehelpers/json_serializable_mobx_typehelpers
