name: json_serializable_fic_typehelpers
description: typehelpers for fast_immutable_collections for json_serializable
version: 1.0.0
homepage: https://github.com/knaeckeKami/json_serializable_immutable_collections/tree/master/


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  fast_immutable_collections: ^2.0.2
  json_serializable: ^6.0.1
  # json_serializable_type_helper_utils: ^3.0.0
  json_serializable_type_helper_utils:
    path: ../json_serializable_type_helper_utils
  analyzer: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
